[package]
name = "chapchap"
version = "0.1.0"
authors = ["Hamid R. K. Pishghadam <hamidrkp@riseup.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = "3.2"
config = "0.10"
chrono = "0.4"
serde = {version = "1.0", features = ["derive"]}
