[[apps]]
name = "Telegram"
enabled = true
slices = [ [18:00:00, 19:00:00] ]
black_list = false
command.regex = "Telegram.*"

[[apps]]
name = "MPV"
enabled = true
slices = [ [20:00:00, 23:59:00] ]
black_list = false
command.plain = "mpv"
args.regex = ".*vid.*"
