[telegram]
enabled = true
slices = [ [09:00:00, 10:00:00], [15:00:00, 16:00:00] ]
black_list = true
command = "telegram-deskto"

[mpv]
enabled = true
slices = [ [18:00:00, 18:07:00], [18:08:00, 18:09:00] ]
black_list = false
command = "mpv"
