[package]
name = "chapchap-ui"
version = "0.1.0"
build = "build.rs"
edition = "2021"

[dependencies]
slint = "1.0"
chapchap-common = { path = "../chapchap-common" }
anyhow = "1.0"
zbus = "3.13"

[build-dependencies]
slint-build = "1.0"
