[package]
name = "chapchap-common"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde", "std", "clock"], default-features = false }
serde = { version = "1", features = ["derive"] }
zbus = "3.12"
