name: Rust release
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: nightly
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [ i686-unknown-linux-gnu, x86_64-unknown-linux-gnu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      # related to https://github.com/actions/runner/issues/2468 
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Install gcc-libs
        run: |
          sudo apt install gcc-multilib 

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          # use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          TAR_NAME=$(printf "chapchap-%s.tar.gz" $(echo ${{ matrix.target }} | sed 's/-unknown//g' ) )

          tar czvf ../../../${TAR_NAME} chapchap
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly
          files: 'chapchap*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
